//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.11 at 10:07:00 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ns.editeur.org/onix/3.0/short", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.editeur.onix.v30.shorts;
