//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.11 at 10:07:00 PM IST 
//


package org.editeur.onix.v30.shorts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b034" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}x409"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}x410" minOccurs="0"/>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b020" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b203"/>
 *           &lt;sequence>
 *             &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b030"/>
 *             &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b031"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{http://ns.editeur.org/onix/3.0/short}b029" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://ns.editeur.org/onix/3.0/short}generalAttributes"/>
 *       &lt;attribute name="refname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="TitleElement"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="shortname">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="titleelement"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "b034",
    "x409",
    "x410",
    "b020",
    "b203",
    "b030",
    "b031",
    "b029"
})
@XmlRootElement(name = "titleelement")
public class Titleelement {

    protected B034 b034;
    @XmlElement(required = true)
    protected X409 x409;
    protected X410 x410;
    protected B020 b020;
    protected B203 b203;
    protected B030 b030;
    protected B031 b031;
    protected B029 b029;
    @XmlAttribute(name = "refname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String refname;
    @XmlAttribute(name = "shortname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String shortname;
    @XmlAttribute(name = "datestamp")
    protected String datestamp;
    @XmlAttribute(name = "sourcetype")
    protected String sourcetype;
    @XmlAttribute(name = "sourcename")
    @XmlSchemaType(name = "anySimpleType")
    protected String sourcename;

    /**
     * Gets the value of the b034 property.
     * 
     * @return
     *     possible object is
     *     {@link B034 }
     *     
     */
    public B034 getB034() {
        return b034;
    }

    /**
     * Sets the value of the b034 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B034 }
     *     
     */
    public void setB034(B034 value) {
        this.b034 = value;
    }

    /**
     * Gets the value of the x409 property.
     * 
     * @return
     *     possible object is
     *     {@link X409 }
     *     
     */
    public X409 getX409() {
        return x409;
    }

    /**
     * Sets the value of the x409 property.
     * 
     * @param value
     *     allowed object is
     *     {@link X409 }
     *     
     */
    public void setX409(X409 value) {
        this.x409 = value;
    }

    /**
     * Gets the value of the x410 property.
     * 
     * @return
     *     possible object is
     *     {@link X410 }
     *     
     */
    public X410 getX410() {
        return x410;
    }

    /**
     * Sets the value of the x410 property.
     * 
     * @param value
     *     allowed object is
     *     {@link X410 }
     *     
     */
    public void setX410(X410 value) {
        this.x410 = value;
    }

    /**
     * Gets the value of the b020 property.
     * 
     * @return
     *     possible object is
     *     {@link B020 }
     *     
     */
    public B020 getB020() {
        return b020;
    }

    /**
     * Sets the value of the b020 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B020 }
     *     
     */
    public void setB020(B020 value) {
        this.b020 = value;
    }

    /**
     * Gets the value of the b203 property.
     * 
     * @return
     *     possible object is
     *     {@link B203 }
     *     
     */
    public B203 getB203() {
        return b203;
    }

    /**
     * Sets the value of the b203 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B203 }
     *     
     */
    public void setB203(B203 value) {
        this.b203 = value;
    }

    /**
     * Gets the value of the b030 property.
     * 
     * @return
     *     possible object is
     *     {@link B030 }
     *     
     */
    public B030 getB030() {
        return b030;
    }

    /**
     * Sets the value of the b030 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B030 }
     *     
     */
    public void setB030(B030 value) {
        this.b030 = value;
    }

    /**
     * Gets the value of the b031 property.
     * 
     * @return
     *     possible object is
     *     {@link B031 }
     *     
     */
    public B031 getB031() {
        return b031;
    }

    /**
     * Sets the value of the b031 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B031 }
     *     
     */
    public void setB031(B031 value) {
        this.b031 = value;
    }

    /**
     * Gets the value of the b029 property.
     * 
     * @return
     *     possible object is
     *     {@link B029 }
     *     
     */
    public B029 getB029() {
        return b029;
    }

    /**
     * Sets the value of the b029 property.
     * 
     * @param value
     *     allowed object is
     *     {@link B029 }
     *     
     */
    public void setB029(B029 value) {
        this.b029 = value;
    }

    /**
     * Gets the value of the refname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefname() {
        return refname;
    }

    /**
     * Sets the value of the refname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefname(String value) {
        this.refname = value;
    }

    /**
     * Gets the value of the shortname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * Sets the value of the shortname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortname(String value) {
        this.shortname = value;
    }

    /**
     * Gets the value of the datestamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatestamp() {
        return datestamp;
    }

    /**
     * Sets the value of the datestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatestamp(String value) {
        this.datestamp = value;
    }

    /**
     * Gets the value of the sourcetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets the value of the sourcetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcetype(String value) {
        this.sourcetype = value;
    }

    /**
     * Gets the value of the sourcename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * Sets the value of the sourcename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcename(String value) {
        this.sourcename = value;
    }

}
